name: fort_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.2.3 #  Properly indented with 2 spaces, ispe dekhna hoga aur
  google_ml_kit: ^0.20.0 # Correct version from pub.dev for ocr (previously tried ^4.1.0)
  image_picker: ^1.0.4 # to capture images
  google_maps_flutter: ^2.3.0 #for map rendering
  dio: ^5.0.2 #for http req
  flutter_polyline_points_plus: ^3.0.0 # Replace flutter_polyline_points with this
  #firebase_database: ^10.2.0
  intl: ^0.18.0
  #firebase_core: ^2.15.0
  # firebase_auth: ^4.16.0
  firebase_core: ^3.13.0      # Upgrade to v3.x
  firebase_auth: ^5.5.2       # Compatible with firebase_core 3.x
  firebase_database: ^11.0.0  # Upgrade to latest
  js: ^0.7.2                  # Add this line
  flutter_dotenv: ^5.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

